### ISSUE TITLE
Use with a custom JSON-LD

### ISSUE THREAD

**Issue by Allsimon** [Kobee1203/schema-org-java#23]
Hello, I'm interested in generating pojo for a customized schema.org. 

It looks like it's not possible with the current version (0.2.2) of your maven plugin.

I'm thinking of something like this:
```
.
├── pom.xml
└── src
    └── main
        └── resources
            └── custom.jsonld
```

with this configuration:

```
    <build>
        <plugins>
            <plugin>
                <groupId>com.weedow</groupId>
                <artifactId>schema-org-generator-maven-plugin</artifactId>
                <version>${schema-org.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <schemaVersion>classpath:/custom.jsonld</schemaVersion>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
```

(not sure about re-using `schemaVersion` though 🤔 )

Are you interested in this functionality ? I think I can contribute it if you want

**Comment by Kobee1203** [comment]
This is an interesting proposal.
However, I don't think the `schemaVersion` field is well suited for this.
Maybe a new field: `schemaResource`?
If you can contribute, it will be with great pleasure :)

**Comment by Kobee1203** [comment]
I have time to deal with this issue.
I have created a branch to take care of this feature: 
https://github.com/Kobee1203/schema-org-java/tree/feature/issue-23

**Comment by Kobee1203** [comment]
Hi @Allsimon 

The latest release 0.3.1 adds a new option, `schemaResource`, to specify a schema resource location to be used for generation.

The value can be either a "classpath:" pseudo URL, a "file:" URL, or a plain file path.

let's assume the following tree structure:
```
.
├── pom.xml
└── src
    └── main
        └── resources
            └── example.jsonld
```

Here is the configuration of the maven plugin
```
<plugin>
    <groupId>com.weedow</groupId>
    <artifactId>schema-org-generator-maven-plugin</artifactId>
    <version>0.3.1</version>
    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <schemaResource>classpath:example.jsonld</schemaResource>
            </configuration>
        </execution>
    </executions>
</plugin>
```
