### ISSUE TITLE
want to set array objects

### ISSUE THREAD

**Issue by mrtylmz** [Kobee1203/schema-org-java#53]
Let's say I want to set multiple objects, for instance, Thing object has a setter for identifier object and I can't add multiple identifier object. It takes just one object, can it take a list of identifier objects? So I will be able to set array objects.

**Comment by Kobee1203** [comment]
I'm working on it when I have some time.

I'm not done yet, I need to make sure the serialization/deserialization works as expected.

The next release will contain this evolution.

**Comment by Kobee1203** [comment]
Done.
It will be available in the next release 0.4.x

**Comment by mrtylmz** [comment]
Thanks, it works as expected in version 0.4.0
